// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Future = require("../src/future.res.js");
var Js_exn = require("rescript/lib/js/js_exn.js");

Future.fold(Future.map(Future.make(function () {
              return new Promise((function (res, _rej) {
                            res(42);
                          }));
            }), (function (res) {
            return res + 1 | 0;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

Future.fold(Future.map(Future.make(function () {
              return new Promise((function (_res, rej) {
                            rej(Js_exn.raiseError("There was a problem"));
                          }));
            }), (function (res) {
            return res + 1 | 0;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

/*  Not a pure module */
