// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Future = require("../src/future.res.js");

var a = Future.make(function () {
      return Promise.resolve(1);
    });

exports.a = a;
/* a Not a pure module */
