// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Future from "../src/future.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";

var a = Future.make((function () {
        return Promise.resolve(1);
      }), undefined);

Future.fold(Future.all2([
          a,
          a
        ]), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

var b = Future.make((function () {
        return Promise.reject(Js_exn.raiseError("There was an error"));
      }), undefined);

Future.fold(Future.all2([
          a,
          b
        ]), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

export {
  a ,
  b ,
}
/* a Not a pure module */
