// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Future from "../src/future.res.mjs";

Future.fold(Future.map(Future.flatMap(Future.$$fetch("http://httpstat.us/200"), (function (res) {
                if (res.ok) {
                  return {
                          TAG: "Ok",
                          _0: res
                        };
                } else {
                  return {
                          TAG: "Error",
                          _0: res.status.toString() + ": " + res.statusText
                        };
                }
              })), (function (res) {
            return res.statusText;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

Future.fold(Future.map(Future.flatMap(Future.$$fetch("http://httpstat.us/500"), (function (res) {
                if (res.ok) {
                  return {
                          TAG: "Ok",
                          _0: res
                        };
                } else {
                  return {
                          TAG: "Error",
                          _0: res.status.toString() + ": " + res.statusText
                        };
                }
              })), (function (res) {
            return res.statusText;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

var request = Future.flatMap(Future.$$fetch("http://httpstat.us/404?sleep=1000"), (function (res) {
        console.log("doing things with response");
        if (res.ok) {
          return {
                  TAG: "Ok",
                  _0: res
                };
        } else {
          return {
                  TAG: "Error",
                  _0: res.status.toString() + ": " + res.statusText
                };
        }
      }));

Future.fold(request, (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

Future.cancel(request);

export {
  request ,
}
/*  Not a pure module */
