// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Future = require("../src/future.res.js");

Future.fold(Future.map(Future.flatMap(Future.make(function () {
                  return fetch("http://httpstat.us/200");
                }), (function (res) {
                if (res.ok) {
                  return {
                          TAG: "Ok",
                          _0: res
                        };
                } else {
                  return {
                          TAG: "Error",
                          _0: res.status.toString() + ": " + res.statusText
                        };
                }
              })), (function (res) {
            return res.statusText;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

Future.fold(Future.map(Future.flatMap(Future.make(function () {
                  return fetch("http://httpstat.us/500");
                }), (function (res) {
                if (res.ok) {
                  return {
                          TAG: "Ok",
                          _0: res
                        };
                } else {
                  return {
                          TAG: "Error",
                          _0: res.status.toString() + ": " + res.statusText
                        };
                }
              })), (function (res) {
            return res.statusText;
          })), (function (prim) {
        console.error(prim);
      }), (function (prim) {
        console.log(prim);
      }));

/*  Not a pure module */
